name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        branch: ["dev"]
    steps:
      - uses: jfrog/frogbot@v2
        env:
          JF_URL: http://172.16.1.14:8082/
          JF_ACCESS_TOKEN: cmVmdGtuOjAxOjAwMDAwMDAwMDA6ZEllUE5jT3hqUm5NWlZSUW1LODh2WmllVnhB
          JF_GIT_TOKEN: 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
          JF_GIT_BASE_BRANCH: dev
